name: bse
version: 0.0.1
description: A minimal web app for the developer that doesn’t want to be confused by too much going on.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  json_object: any
  route_hierarchical: '>=0.5.0 <0.6.0'
  sass: '>=0.4.0 <0.5.0'
  script_inliner: '>=0.0.3 <0.1.0'
transformers:
- script_inliner
